### ISSUE TITLE
Use jshintrc from file's parent directory, not current working directory

### ISSUE THREAD

**Issue by mxdubois** [wookiehangover/jshint.vim#37]
Seems like jshint is run from the directory at which vim was opened  I think it should probably run in the directory of the file that it is linting.

**Here's my case:**
I have a project structure like this:

    project/
      .jshintrc
      src/
      test/
        .jshintrc

`test/.jshintrc` defines globals for mocha:
```json
{
  "extends" : "../.jshintrc",
  "globals"   : {
    "describe"   : false,
    "it"         : false,
    "before"     : false,
    "beforeEach" : false,
    "after"      : false,
    "afterEach"  : false
  }
}
```

If I open a test file like this `$ vim test/myTest.js` it works fine.
If I open vim from the project root and open my test file using nerdTree or `:open test/myTest.js`, then it doesn't pick up `test/.jshintrc`.

**Comment by mattmarcum** [comment]
more than that, it should check every directory up the tree until it gets to the project root.  Ember-cli projects have .jshintrc in project root and then a different one in the tests folder, and the tests folder has nested folders...
