### ISSUE TITLE
jshint.vim not working in vim 7.4 and ubuntu 14.04

### ISSUE THREAD

**Issue by belveryin** [wookiehangover/jshint.vim#43]
I've just installed jshint with pathogen and nothing happens when I save a file. It doesn't add JSHintUpdate to my vim and there is nothing on vim output.

PS: node is in the path

**Comment by eddiemonge** [comment]
Is this still a problem? If so I will reopen

**Comment by belveryin** [comment]
Not a problem anymore. Thanks!
