### ISSUE TITLE
Why does jshint.vim call JSHintUpdate on dd, dw, u, <C-r> ?

### ISSUE THREAD

**Issue by yuzeh** [wookiehangover/jshint.vim#44]
See: https://github.com/wookiehangover/jshint.vim/blob/master/ftplugin/javascript/jshint.vim#L66-69

This is causing a noticeable slowdown, as `JSHintUpdate` calls `JSHint`, which kind of defeats the purpose of setting `g:JSHintUpdateWriteOnly = 1`.

**Comment by eddiemonge** [comment]
Thats a bug. There should be a check at https://github.com/wookiehangover/jshint.vim/blob/master/ftplugin/javascript/jshint.vim#L134 for JSHintUpdateWriteOnly
